#!/bin/bash

define host {
 use linux-server
 host_name $minion_name
 alias $minion_name
 address $minion_ip
 max_check_attempts 5
 check_period 24x7
 notification_interval 30
 notification_period 24x7
}

define service {
 use generic-service
 host_name $minion_name
 service_description CPU load
 check_command check_nrpe!check_load
}

define service {
 use generic-service
 host_name your_monitored_server_host_name
 service_description /dev/sda1 free space
 check_command check_nrpe!check_sda1
}


# /usr/local/nagios/etc/servers/$minion_name.cfg
