#! /bin/bash

#installation file for slavevm_syslog_install

sudo apt-get install syslog-ng

sudo sed -i -e 's+%cfg_dir=/usr/local/nagios/etc/servers%cfg_dir=/usr/local/nagios/etc/servers%g' /etc/syslog-ng/syslog-ng.conf

#make empty file by deleting it
cd /etc/syslog-ng/
sudo rm /etc/syslog-ng/syslog-ng.conf
#make new empty file
sudo touch /etc/syslog-ng/syslog-ng.conf

echo -e "Please insert the monitoring host ip"
read -p 'Saltstack Master name: ' hostip

echo '@version: 3.5
@include "scl.conf"
@include "`scl-root`/system/tty10.conf"


###################
# Sources
###################
source s_apache {
 file(“/var/log/apache2/access.log” flags(no-parse));
 file(“/var/log/apache2/error.log” flags(no-parse));
};

###################
# Destinations
###################
destination d_network { tcp("$hostip" port(601)); };

##################
# Log paths
##################
log { source(s_apache); destination(d_network); };
' >> /etc/syslog-ng/syslog-ng.conf

sudo systemctl restart syslog-ng
