#!/bin/bash

#this will be the installation script for the slavevms
:'
#make the scripts executable otherwise not worky worky

echo -e "Please insert the nagios Master IP"
read -p 'Nagios Master IP: ' ip

echo -e "Please insert the nagios minion IP"
read -p 'Nagios Master IP: ' ipslave



#prerequisites
sudo apt-get install -y -q autoconf gcc libc6 libmcrypt-dev make libssl-dev wget bc gawk dc build-essential snmp libnet-snmp-perl gettext

#download the source and extract
cd ~
curl -L -O http://nagios-plugins.org/download/nagios-plugins-2.2.1.tar.gz
tar zxf nagios-plugins-.tar.gz

#compile & install nagios plugins
cd /tmp/nagios-plugins-release-2.2.1/
sudo ./tools/setup
sudo ./configure
sudo make
sudo make install

#nagios user creation
sudo useradd nagios


#NRPE installation
#download source and extraction
cd /tmp
wget https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz
tar zxf nrpe-3.2.1.tar.gz

#compile and install nrpe
cd /tmp/nrpe-*
sudo ./configure
sudo make check_nrpe
sudo make install-plugin

#here we change the allowed_hosts to the masterVM's IP adress.
sudo sed -i -e "s++127.0.0.1,::1,your_nagios_server_private_ip+127.0.0.1,::1,$ip+g" /usr/local/nagios/etc/nrpe.cfg
sudo nano /usr/local/nagios/etc/nrpe.cfg


#restart nrpe
sudo systemctl start nrpe

#to check if the configuration has been succesfull, execute this command:

/usr/local/nagios/libexec/check_nrpe -H remote_host_ip
#if the output is NRPE v3.2.1 , there is a connection.

#change the folowing lines to the masterVM's IP adress and the disk we want to monitor(sda1 in dit geval)
sudo nano /usr/local/nagios/etc/nrpe.cfg

server_address=$ipslave

command[check_vda1]=/usr/lib/nagios/plugins/check_disk -w 20% -c 10% -p /dev/sda1

#restart nrpe
sudo systemctl restart nrpe
'
: #!/bin/bash

mstr_ip=$1
minion_ip=$2

sudo adduser nagios

sudo apt-get update
sudo apt-get install build-essential libgd2-xpm-dev openssl libssl-dev unzip

cd ~
curl -L -O http://nagios-plugins.org/download/nagios-plugins-2.2.1.tar.gz
tar zxf nagios-plugins-.tar.gz

cd nagios-plugins-
./configure --with-nagios-user=nagios --with-nagios-group=nagios --with-openssl

make
sudo make install

cd ~
curl -L -O https://github.com/NagiosEnterprises/nrpe/releases/download/nrpe-3.2.1/nrpe-3.2.1.tar.gz
tar zxf nrpe-.tar.gz

cd nrpe-
./configure --enable-command-args --with-nagios-user=nagios --with-nagios-group=nagios --with-ssl=/usr/bin/openssl --with-ssl-lib=/usr/lib/x86_64-linux-gnu

make all
sudo make install
sudo make install-config
sudo make install-init
