#!/bin/bash

echo -e "Please insert the nagios Minion IP 10.0.0.16"
read -p 'Nagios Minion IP: ' ipslave

echo -e "Please insert the nagios minion hostname minion"
read -p 'Nagios Minion HostName: ' nameslave

#copying our template to make a new minion.cfg file on the master.
